FROM node:16
# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY ../package.json ./
COPY ../yarn.lock ./

RUN yarn install


COPY app.js .

EXPOSE 5001

CMD [ "node", "app.js" ]