FROM node:16
# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json ./
COPY yarn.lock ./

RUN yarn install

COPY ajv/app.js .
COPY schemas ../schemas

EXPOSE 5002

CMD [ "node", "app.js" ]
