FROM node:24
# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json ./
COPY package-lock.json ./

COPY ajv/app.js .
COPY schemas ../schemas

RUN npm install --production=true

ENV AJV_VALIDATOR_PORT=5002
ENV DEBUG=ajv-schema-validator

WORKDIR /usr/src

CMD [ "node", "app/app.js" ]
