name: Main

on:
  push:
    branches:
      - main

jobs:
  docker-push:
      permissions:
        contents: read
        id-token: write
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

        - id: auth
          name: Authenticate to Google Cloud
          uses: google-github-actions/auth@71f986410dfbc7added4569d411d040a91dc6935 # v2.1.8
          with:
            token_format: 'access_token'
            workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
            service_account: ${{ secrets.SERVICE_ACCOUNT }}

        - name: Build
          run: |
            docker build -t ${{ secrets.GAR_LOCATION }}/${{ secrets.GAR_PROJECT_ID }}/docker-images/eq-questionnaire-validator:latest .
            docker build -f Dockerfile-ajv -t${{ secrets.GAR_LOCATION }}/${{ secrets.GAR_PROJECT_ID }}/docker-images/eq-questionnaire-validator:latest-ajv .
        - name: Push
          run: |
            gcloud auth configure-docker ${{ secrets.GAR_LOCATION }}
            echo "Pushing to GAR with tag [latest]"
            docker push ${{ secrets.GAR_LOCATION }}/${{ secrets.GAR_PROJECT_ID }}/docker-images/eq-questionnaire-validator:$TAG
            echo "Pushing with tag [$TAG-ajv]"
            docker push ${{ secrets.GAR_LOCATION }}/${{ secrets.GAR_PROJECT_ID }}/docker-images/eq-questionnaire-validator:$TAG-ajv